test_that('WHO 2026 population has the published age groups and types', {
  expect_s3_class(who_std_pop, 'tbl_df')
  expect_named(who_std_pop, c('age_group', 'age_start', 'weight', 'std_million'))
  expect_equal(nrow(who_std_pop), 18L)
  expect_type(who_std_pop$age_start, 'integer')
  expect_type(who_std_pop$weight, 'double')
  expect_type(who_std_pop$std_million, 'double')
  expect_equal(who_std_pop$age_start, seq.int(0L, 85L, 5L))
  expect_equal(tail(who_std_pop$age_group, 1), '85+')
  expect_false(anyNA(who_std_pop))
  expect_equal(anyDuplicated(who_std_pop$age_group), 0L)
  expect_true(all(who_std_pop$weight >= 0))
})
test_that('WHO 2026 rounded percentages are explicitly normalized', {
  published <- c(7.21, 7.13, 7.11, 7.12, 7.15, 7.08, 6.89, 6.66, 6.35,
                 6.04, 5.75, 5.41, 4.97, 4.43, 3.77, 2.98, 2.08, 1.89)
  expect_equal(sum(published), 100.02)
  expect_equal(who_std_pop$weight, published / 100.02 * 100)
  expect_equal(sum(who_std_pop$weight), 100)
  expect_equal(sum(who_std_pop$std_million), 1e6)
  expect_equal(who_std_pop$std_million, who_std_pop$weight * 1e4)
})
test_that('age standardization consumes WHO 2026 weights directly', {
  pop <- rep(10000, 18)
  count <- seq_len(18)
  manual <- sum(who_std_pop$weight / 100 * count / pop) * 1e5
  expect_equal(age_standardize(count, pop, who_std_pop$weight), manual)
  expect_equal(age_standardize(count, pop, who_std_pop$std_million), manual)
  expect_equal(age_standardize(rep(10, 18), pop, who_std_pop$weight), 100)
})
